apiVersion: apps/v1
kind: Deployment
metadata:
  name: ndots-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ndots-webhook
  template:
    metadata:
      labels:
        app: ndots-webhook
    spec:
      containers:
        - name: webhook
          image: ECR_IMAGE_URL:latest
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
          env:
            - name: LOG_LEVEL
              value: info #
      volumes:
        - name: tls
          secret:
            secretName: ndots-webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  name: ndots-webhook-svc
  namespace: kube-system
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: ndots-webhook
